Allow creation of missing lines via the track menu
teamspatzenhirn/Simulator pull request #9
Opened 2022-10-18 18:59 UTC by authaldo

Follow-up of #7 to improve the possible line types further.

Changes:
 - minor whitespace fixes
 - track lines can now be easily hidden in the track interface

![grafik](https://user-images.githubusercontent.com/45536968/196518250-8b2771c8-bb31-437c-895f-c9464d85f1ee.png)

Note: 

This MR doesn't include any measures to avoid the construction of illegal courses (e.g. it is possible to hide all three lines).
For now, we expect the user to handle the new feature with care as the check is more difficult than requiring one out of three lines being visible (the rulebook specifies a maximum length for two missing lines which could span over more than one segment).

2022-10-18 19:05 UTC, fgardt approved these changes

2022-10-19 09:58 UTC, ottojo requested changes

2022-10-19 09:59 UTC, ottojo commented on src/Storage.cpp
> +    tryGet(jsonTrack, "rightLineMissing", track->rightLineMissing);
also ich sehe dass die klasse das schon mit false initialisiert, aber ich finde das sollte hier definiertes resultat haben was nicht vom zustand vorher abhängig ist. ich vermute sonst kann auch so spaß passieren wie reloaden und der leftLineMissing zustand wird nicht zurückgesetzt?

2022-10-19 11:53 UTC, authaldo commented on src/modules/GuiModule.cpp
> +                    ImGui::PushID("Center");
Das kam durch trial and error weil die Checkboxen initial Probleme hatten und ich die IDs im Verdacht hatte. Die werden über diesen Stack gebildet, sodass durch das Pushen von unterschiedlichen Werten hoffentlich alle Kollisionen beseitigt werden

2022-10-19 12:23 UTC, authaldo commented on src/Storage.cpp
> +    tryGet(jsonTrack, "rightLineMissing", track->rightLineMissing);
Ich bin da kein Fan von doppelten defaults mit einem in der Klasse und ein zweiter nur für das JSON...

2022-10-20 09:04 UTC, ottojo approved these changes
nicht resolved, aber egal genug dass man nicht drauf warten will

2022-10-20 09:04 UTC, merged